# Generated by Django 5.1.4 on 2025-02-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('num_pages', models.IntegerField()),
                ('college_or_school', models.CharField(max_length=255)),
                ('locations', models.JSONField()),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resource_file', models.FileField(upload_to='resources/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.user')),
            ],
        ),
    ]
